### ISSUE TITLE
Items Inventory don't get reduced

### ISSUE THREAD

**Issue by ravindug** [micwallace/wallacepos#100]
[after sales inventory items don't get reduced]

After I finish sales items in inventory don't get reduced and I even can sell out of stock items no warning displayed too.

**Comment by micwallace** [comment]
I can't reproduce the stock level issue. Are you sure you're not looking at the warehouse stock? Stock is removed from the location inventory. 

There is no stock warning by design. If a customer walks up to the register, you still need to be able to ring up that item even if it's out of stock. The stock level will go into negative but only once it's tracked at that location (using transfer/add stock function).
