### ISSUE TITLE
Cannot Install on Localhost

### ISSUE THREAD

**Issue by lovelamp** [micwallace/wallacepos#21]
I can't seem to get this to work on localhost.

Windows 8.1 with a working  XAMPP.
Please help. What am i doing wrong? Please see the attached image.

Thanks.
![wallace_installer](https://cloud.githubusercontent.com/assets/14177346/13511208/9bb0fd12-e194-11e5-9ebf-99c320a4937d.png)

**Comment by micwallace** [comment]
WallacePOS is currently not tested or supported on XAMPP.
Please consult Apache error logs for any clues.

**Comment by ais-one** [comment]
I got it to work on xampp (v5.6.19 - Windows 32-bit). This comment will be edited as and when problems are found. My path to the application is <drive>\xampp\htdocs\wpos


Start With Xampp Configuration...

1. enable mod_proxy_http & mod_proxy_wstunnel in <drive>\xampp\apache\conf\httpd.conf
mod_rewrite already enabled

2. curl and gd modules seem to also have been enabled
extension=php_curl.dll
extension=php_gd2.dll

3. edit <drive>\xampp\apache\conf\extra\httpd-vhosts.conf

````
<VirtualHost *:443>

DocumentRoot /xampp/htdocs/wpos
ServerName 127.0.0.1

#ErrorLog ${APACHE_LOG_DIR}/error.log
#CustomLog ${APACHE_LOG_DIR}/access.log combined

SSLEngine on
SSLCipherSuite !ADH:!DSS:!RC4:HIGH:+3DES:+RC4
SSLProtocol all -SSLv2 -SSLv3
SSLCertificateFile /xampp/apache/conf/ssl.crt/server.crt
SSLCertificateKeyFile /xampp/apache/conf/ssl.key/server.key

<Directory /xampp/htdocs/wpos >
	AllowOverride all
</Directory>

# WSPROXY CONF
ProxyRequests Off
ProxyPreserveHost On
<Proxy *>
	Order deny,allow
	Allow from all
</Proxy>
ProxyPass /socket.io/1/websocket/ ws://localhost:8080/socket.io/1/websocket/
ProxyPassReverse /socket.io/1/websocket/ ws://localhost:8080/socket.io/1/websocket
ProxyPass /socket.io/ http://localhost:8080/socket.io/
ProxyPassReverse /socket.io/ http://localhost:8080/socket.io/
<Location /socket.io>
	Order allow,deny
	Allow from all
</Location>
</VirtualHost>

````
Next nodejs, yucks...

0. add C:\xampp to the PATH environment variable on the machine, reboot apache control program

1. download node,exe and npm (and npm's node_modules folder) and place it in the folder <drive>\xampp\

2. run npm install socket.io as per instructions (my node_modules/socket.io folder is in <drive>\xampp\htdocs\wpos\ folder)


FINALLY...

Run https://127.0.0.1/installer

Ignore write-permission errors (the other statuses must be green though) and proceed to configure the database. I forgot to note down what it was but there were 2 errors regarding read/write permissions.

rename <drive>\xampp\htdocs\wpos\docs-template to <drive>\xampp\htdocs\wpos\docs (it was not renamed as it was caused by one of the errors above)

And I manage to get it working well on XAMPP (Windows 32-bit) so far... until someone else runs into problem.
