### ISSUE TITLE
dbconfig_template issue

### ISSUE THREAD

**Issue by captainwasabi** [micwallace/wallacepos#5]
Line 1 is 

    <?

Line 1 should be:

    <?php

**Comment by micwallace** [comment]
Hi,

This is only because your using an older version of php. I think short tags can be turned on in your version but its best to upgrade to version >=5.5.

Cheers,
Michael

On 3 May 2015 4:20:19 AM AEST, captainwasabi <notifications@github.com> wrote:
>Line 1 is 
>
>    <?
>
>Line 1 should be:
>
>    <?php
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/wallacepos/issues/5

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
