### ISSUE TITLE
(Service Unavailable) on /admin/#!realtime  when start socket.io

### ISSUE THREAD

**Issue by OmarSari** [micwallace/wallacepos#57]
I got an error on console:  VM26939:2 GET https://localhost/socket.io/1/?t=1472386247234 503 (Service Unavailable)
on /admin/#!realtime  when start socket.io.
Notes: 
I use Apache server listens to port 80 AND Nodejs listens to port 8085.
AND I use windows 7 operating system.

Sincerely

**Comment by micwallace** [comment]
The node.js feed server runs by default on port 8080.
If you want to run it on a different port you need to reconfigure apache wsproxy as per installation guide:

```
ProxyPass /socket.io/1/websocket/ ws://localhost:8085/socket.io/1/websocket/
ProxyPassReverse /socket.io/1/websocket/ ws://localhost:8085/socket.io/1/websocket
ProxyPass /socket.io/ http://localhost:8085/socket.io/
ProxyPassReverse /socket.io/ http://localhost:8085/socket.io/
```
You also need to be running socket.io 0.9.x

**Comment by OmarSari** [comment]
I do these steps, and I get the same error.
When I start socket.io and do logout and then do login, it give me the logs:

   info  - socket.io started
   debug - client authorized
   info  - handshake authorized hsd56svRa1aHzbY7KU5f
   debug - setting request GET /socket.io/1/websocket/hsd56svRa1aHzbY7KU5f
   debug - set heartbeat interval for client hsd56svRa1aHzbY7KU5f
   debug - client authorized for
   debug - websocket writing 1::
Authorised by hashkey: dgqsy8DgvyKl6RhCngOuFzNosbnThPZnMHCpZZm58GGb7Nnr2Y1tzVVud
RBAj1ad
   debug - got disconnection packet
   info  - transport end by forced client disconnection
   debug - websocket writing 0::
   info  - transport end (booted)
   debug - set close timeout for client hsd56svRa1aHzbY7KU5f
   debug - cleared close timeout for client hsd56svRa1aHzbY7KU5f
   debug - cleared heartbeat interval for client hsd56svRa1aHzbY7KU5f
   debug - discarding transport

**Comment by micwallace** [comment]
You may need to restart Apache for updated config to take effect.

The included log shows correct operation of PHP talking to node.js (no errors). No connection from the browser is shown which suggests mod_wsproxy is not correctly configured or not working. Try troubleshooting the proxy connection. If the issue persists, please submit another issue using the new issues template.

Also I see you are new to Github. Please only submit issues to repositories if you can verify that the problem exists in that specific software. Your issues submitted to socket.io for instance, are invalid. The problem is with your configuration or WallacePOS, nothing to do with socket.io. Furthermore you need to provide more information, especially on how to recreate the issue. How can anybody help if they can't recreate the issue? Anyway just thought I'd fill you in :+1:

**Comment by micwallace** [comment]
This may also help:
https://github.com/micwallace/wallacepos/issues/54

**Comment by OmarSari** [comment]
Thank you
